name: Code Checks

on:
  push:
    branches: ['*']

  pull_request:

  workflow_dispatch:

jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: |
          requirements-dev.txt
          requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements-dev.txt

    - name: Code checks
      run: export SKIP=no-commit-to-branch; pre-commit run --all
