name: Generate and Commit Changelog

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - ".addon/modules/"
      - ".vscode/"
      - "changelog.md"
      - "readme.md"

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -g conventional-changelog-cli

      - name: Generate changelog
        run: conventional-changelog -p angular -i changelog.md -s

      - name: Clean up changelog formatting
        run: |
          # Remove consecutive blank lines
          sed -i '/^$/N;/^\n$/D' changelog.md

      - name: Check for changes in changelog.md
        id: check_changes
        run: |
          if git diff --quiet changelog.md; then
            echo "No changes in changelog.md"
            echo "changelog_modified=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected in changelog.md"
            echo "changelog_modified=true">> "$GITHUB_OUTPUT"
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changelog_modified == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'changelog.md'
          default_author: github_actions
          message: 'doc: Update changelog [skip ci]'
          pathspec_error_handling: exitImmediately
          push: true
